name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - '**/package.json'
      - '**/tsconfig*.json'
      - '**/jest.config.ts'
      - '**/*.{ts,tsx}'
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Javascript Tests
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    env:
      BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm test
