name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Javascript Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    env:
      BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npx vitest --coverage
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1
